library(dplyr)
library(lubridate)

stormdata_filename <- "repdata_data_StormData.csv"
stormdata_filepath <- file.path("./data/", stormdata_filename)

if (!exists("stormdata")) {
  stormdata <- read.csv(stormdata_filepath)
}

#  Official event types
official_event_types <- c("ASTRONOMICAL LOW TIDE", "AVALANCHE", "BLIZZARD", "COASTAL FLOOD",
                          "COLD/WIND CHILL","DEBRIS FLOW", "DENSE FOG", "DENSE SMOKE",
                          "DROUGHT", "DUST DEVIL","DUST STORM", "EXCESSIVE HEAT", 
                          "EXTREME COLD/WIND CHILL", "FLASH FLOOD", "FLOOD", "FROST/FREEZE",
                          "FUNNEL CLOUD","FREEZING FOG", "HAIL", "HEAT", "HEAVY RAIN", "HEAVY SNOW",
                          "HIGH SURF", "HIGH WIND", "HURRICANE (TYPHOON)", "ICE STORM",
                          "LAKE-EFFECT SNOW", "LAKESHORE FLOOD", "LIGHTNING",
                          "MARINE HAIL", "MARINE HIGH WIND", "MARINE STRONG WIND",
                          "MARINE THUNDERSTORM WIND", "RIP CURRENT", "SEICHE", "SLEET",
                          "STORM SURGE/TIDE", "STRONG WIND", "THUNDERSTORM WIND",
                          "TORNADO", "TROPICAL DEPRESSION", "TROPICAL STORM", "TSUNAMI",
                          "VOLCANIC ASH","WATERSPOUT", "WILDFIRE", "WINTER STORM",
                          "WINTER WEATHER")

replacement_list <- list(
  c("ASTRONOMICAL LOW TIDE"),
  c("AVALANCHE", "AVALANCE", "HEAVY SNOW/BLIZZARD/AVALANCHE"),
  c("BLIZZARD", "HIGH WIND/BLIZZARD", "HEAVY SNOW/BLIZZARD",
    "BLIZZARD AND EXTREME WIND CHIL", "BLIZZARD/HEAVY SNOW", "GROUND BLIZZARD",
    "BLIZZARD AND HEAVY SNOW", "BLIZZARD SUMMARY", "BLIZZARD WEATHER",
    "BLIZZARD/FREEZING RAIN", "BLIZZARD/HIGH WIND", "BLIZZARD/WINTER STORM",
    "HIGH WIND/ BLIZZARD", "HIGH WIND/BLIZZARD/FREEZING RA", "ICESTORM/BLIZZARD"
  ),
  c("COASTAL FLOOD", "COASTAL FLOODING", "COASTAL FLOODING/EROSION", "COASTAL/TIDAL FLOOD",
    "BEACH EROSION/COASTAL FLOOD", "COASTAL  FLOODING/EROSION", "COASTAL EROSION",
    "COASTALFLOOD", "HEAVY SURF COASTAL FLOODING", "HIGH WINDS/COASTAL FLOOD",
    "CSTL FLOODING/EROSION", "EROSION/CSTL FLOOD", "TIDAL FLOODING", "TIDAL FLOOD"
    ),
  c("COLD/WIND CHILL", "COLD", "HIGH WIND/LOW WIND CHILL", "HIGH WIND/WIND CHILL",
    "HIGH WIND/WIND CHILL/BLIZZARD", "WIND CHILL", "COLD WIND CHILL TEMPERATURES",
    "LOW WIND CHILL", "SNOW- HIGH WIND- WIND CHILL", "WIND CHILL/HIGH WIND"
    ),
  c("DEBRIS FLOW"),
  c("DENSE FOG", "FOG", "PATCHY DENSE FOG", "FOG AND COLD TEMPERATURES", "VOG"),
  c("DENSE SMOKE", "SMOKE"),
  c("DROUGHT", "UNSEASONABLY DRY", "DROUGHT/EXCESSIVE HEAT", "EXCESSIVE HEAT/DROUGHT",
    "HEAT DROUGHT", "HEAT WAVE DROUGHT", "HEAT/DROUGHT"
    ),
  c("DUST DEVIL", "DUST DEVEL", "DUST DEVIL WATERSPOUT"),
  c("DUST STORM", "BLOWING DUST", "SAHARAN DUST", "DUST STORM/HIGH WINDS",
    "DUSTSTORM", "HIGH WINDS DUST STORM"),
  c("EXCESSIVE HEAT"),
  c("EXTREME COLD/WIND CHILL", "EXTREME COLD", "RECORD COLD", "EXTREME WINDCHILL",
    "BITTER WIND CHILL TEMPERATURES", "BITTER WIND CHILL", "EXTREME WIND CHILL/BLOWING SNO",
    "EXTREME WIND CHILLS", "EXTREME WIND CHILL", "EXTREME WINDCHILL TEMPERATURES",
    "HIGH WINDS AND WIND CHILL", "UNSEASONABLY COLD", "PROLONG COLD", "UNUSUALLY COLD",
    "COLD TEMPERATURES", "COLD WEATHER", "EXTREME/RECORD COLD", "COLD WAVE",
    "COLD TEMPERATURE", "EXCESSIVE COLD", "COLD AND WET CONDITIONS", "COLD/WINDS",
    "EXTENDED COLD", "RECORD  COLD", "SEVERE COLD", "UNSEASONABLE COLD",
    "LOW TEMPERATURE", "RECORD LOW", "LOW TEMPERATURE RECORD",
    "BLOWING SNOW- EXTREME WIND CHI", "BLOWING SNOW/EXTREME WIND CHIL"
    ),
  c("FLASH FLOOD", "FLASH FLOODING", "FLOOD/FLASH FLOOD", "FLASH FLOODS", 
    "FLASH FLOODING/FLOOD", "FLASH FLOOD/FLOOD", "FLASH FLOOD FROM ICE JAMS",
    "FLOOD FLASH", "FLASH FLOOD - HEAVY RAIN", "FLASH FLOOD/ FLOOD", "FLOOD/FLASH",
    "FLOOD/FLASH FLOODING", "FLASH FLOOD LANDSLIDES", "FLASH FLOOD WINDS", "FLASH FLOOD/",
    "FLASH FLOOD/ STREET", "FLASH FLOOD/HEAVY RAIN", "FLASH FLOOD/LANDSLIDE",
    "FLASH FLOOODING", "FLOOD FLOOD/FLASH", "FLOOD/FLASH/FLOOD", "FLOOD/FLASHFLOOD",
    "LOCAL FLASH FLOOD"
    ),
  c("FLOOD", "URBAN/SML STREAM FLD", "URBAN FLOOD", "URBAN FLOODING", "FLOODING",
    "STREET FLOOD", "RIVER FLOOD", "URBAN/SMALL STREAM FLOOD", "RIVER FLOODING",
    "LANDSLIDE/URBAN FLOOD", "URBAN FLOOD LANDSLIDE", "URBAN/SMALL STREAM",
    "URBAN AND SMALL STREAM FLOODIN", "SMALL STREAM/URBAN FLOOD",
    "URBAN/SMALL STREAM FLOODING", "URBAN AND SMALL STREAM",
    "URBAN AND SMALL STREAM FLOOD", "URBAN FLOODS", "URBAN/STREET FLOODING",
    "SMALL STREAM AND URBAN FLOOD", "URBAN AND SMALL", "URBAN SMALL STREAM FLOOD",
    "URBAN/SMALL", "URBAN/SMALL STREAM  FLOOD", "MUD SLIDES URBAN FLOODING",
    "SMALL STREAM AND URBAN FLOODIN", "SMALL STREAM URBAN FLOOD", "URBAN SMALL",
    "URBAN/SMALL FLOODING", "URBAN/SMALL STRM FLDG", "URBAN/SML STREAM FLDG",
    "SML STREAM FLD", "SMALL STREAM FLOOD", "FLOOD/RAIN/WINDS", "ICE JAM FLOODING",
    "SNOWMELT FLOODING", "MINOR FLOODING", "SMALL STREAM FLOODING", "FLOODS",
    "MAJOR FLOOD", "STREET FLOODING", "BEACH FLOOD", "RIVER AND STREAM FLOOD",
    "RURAL FLOOD", "BREAKUP FLOODING", "FLOOD WATCH/", "FLOOD/RAIN/WIND",
    "FLOOD/RIVER FLOOD", "HIGHWAY FLOODING", "ICE JAM FLOOD (MINOR",
    "LOCAL FLOOD", "MINOR FLOOD", "STREAM FLOODING"
    ),
  c("FROST/FREEZE", "FREEZE", "FROST", "COLD AND FROST", "EARLY FROST",
    "RECORD COLD/FROST", "FIRST FROST", "FROST\\FREEZE", "DAMAGING FREEZE",
    "HARD FREEZE", "AGRICULTURAL FREEZE", "EARLY FREEZE", "LATE FREEZE"
    ),
  c("FUNNEL CLOUD", "FUNNEL CLOUDS", "WATERSPOUT FUNNEL CLOUD", "FUNNEL CLOUD.",
    "WALL CLOUD/FUNNEL CLOUD", "ROTATING WALL CLOUD", "WALL CLOUD",
    "LARGE WALL CLOUD", "FUNNEL CLOUD/HAIL"
    ),
  c("FREEZING FOG", "GLAZE", "GLAZE ICE", "ICE FOG"),
  c("HAIL", "SMALL HAIL", "HAIL 75", "HAIL 0.75", "HAIL 100", "HAIL 175",
    "NON SEVERE HAIL", "HAIL 1.00", "HAIL 1.75", "HAIL 275", "HAIL/WIND",
    "HAILSTORM", "HAIL 150", "HAIL 80", "HAIL DAMAGE", "HAIL/WINDS", "DEEP HAIL",
    "GUSTY WIND/HAIL", "HAIL 0.88", "HAIL 075", "HAIL 088", "HAIL 1.75)",
    "HAIL 125", "HAIL 200", "HAIL 225", "HAIL 450", "HAIL 88", "HAIL ALOFT",
    "HAIL FLOODING", "HAIL STORM", "HAIL(0.75)", "HAIL/ICY ROADS", "HAILSTORMS",
    "LATE SEASON HAIL", "WIND/HAIL"
    ),
  c("HEAT", "RECORD WARMTH", "UNSEASONABLY WARM", "RECORD HEAT", "HEAT WAVE",
    "EXTREME HEAT", "RECORD TEMPERATURE", "UNSEASONABLY WARM AND DRY",
    "UNSEASONABLY HOT", "UNUSUAL WARMTH", "RECORD/EXCESSIVE HEAT", "HEAT WAVES",
    "HEATBURST", "RECORD HEAT WAVE", "ABNORMAL WARMTH", "PROLONG WARMTH",
    "UNUSUALLY WARM", "UNSEASONABLY WARM YEAR", "UNSEASONABLY WARM/WET",
    "UNUSUAL/RECORD WARMTH", "RECORD WARM", "RECORD WARM TEMPS.",
    "UNSEASONABLY WARM & WET", "VERY WARM", "WARM DRY CONDITIONS", "WARM WEATHER",
    "HOT AND DRY","HOT SPELL", "DRY HOT WEATHER", "HOT PATTERN", "HOT WEATHER",
    "HOT/DRY PATTERN", "RECORD HIGH", "RECORD HIGH TEMPERATURE", "RECORD HIGH TEMPERATURES",
    "HIGH TEMPERATURE RECORD"
    ),
  c("HEAVY RAIN", "HEAVY RAINS", "HEAVY RAINS/FLOODING", "HEAVY RAIN AND WIND",
    "HEAVY RAIN/WIND", "HEAVY RAINFALL", "FLOOD & HEAVY RAIN", "HEAVY RAIN/FLOODING",
    "HEAVY RAIN/SEVERE WEATHER", "FLOODING/HEAVY RAIN",
    "HEAVY RAIN AND FLOOD", "HEAVY RAIN EFFECTS", "HEAVY RAIN; URBAN FLOOD WINDS;",
    "HEAVY RAIN/HIGH SURF", "HEAVY RAIN/LIGHTNING", "HEAVY RAIN/MUDSLIDES/FLOOD",
    "HEAVY RAIN/SMALL STREAM URBAN", "HEAVY RAIN/SNOW", "HEAVY RAIN/URBAN FLOOD",
    "HIGH WINDS HEAVY RAINS", "HIGH WINDS/HEAVY RAIN", "LIGHTNING AND HEAVY RAIN",
    "LIGHTNING/HEAVY RAIN", "LOCALLY HEAVY RAIN", "RAIN (HEAVY)", "RAIN",
    "RECORD RAINFALL", "MONTHLY RAINFALL", "EXCESSIVE RAIN", "RAIN/SNOW",
    "EXCESSIVE RAINFALL", "PROLONGED RAIN", "HVY RAIN", "RECORD LOW RAINFALL",
    "UNSEASONAL RAIN", "EARLY RAIN", "GUSTY WIND/HVY RAIN", "GUSTY WIND/RAIN",
    "RAIN AND WIND", "RAIN DAMAGE", "RAIN/WIND", "RAINSTORM", "RECORD/EXCESSIVE RAINFALL",
    "SNOW/RAIN", "TORRENTIAL RAIN", "TORRENTIAL RAINFALL", "SUMMARY OF JULY 11"
    ),
  c("HEAVY SNOW", "SNOW", "LIGHT SNOW", "MODERATE SNOWFALL", "HEAVY SNOW/FREEZING RAIN",
    "HEAVY SNOW   FREEZING RAIN", "HEAVY SNOW SQUALLS", "SNOW SQUALLS",
    "SNOW SQUALL", "HEAVY SNOW-SQUALLS", "HEAVY SNOW/SQUALLS", "HEAVY SNOW SQUALLS",
    "HEAVY SNOW-SQUALLS", "HEAVY SNOW/ICE", "HEAVY SNOW AND ICE",
    "HEAVY SNOW/SQUALLS", "SNOW AND HEAVY SNOW", "HEAVY SNOW & ICE",
    "HEAVY SNOW AND", "HEAVY SNOW AND STRONG WINDS", "HEAVY SNOW ANDBLOWING SNOW",
    "HEAVY SNOW SHOWER", "HEAVY SNOW/BLOWING SNOW", "HEAVY SNOW/HIGH",
    "HEAVY SNOW/SLEET", "HEAVY SNOW/WIND", "HEAVY SNOWPACK", "SNOW/HEAVY SNOW",
    "EXCESSIVE SNOW", "RECORD SNOW", "RECORD SNOWFALL", "RECORD WINTER SNOW",
    "NEAR RECORD SNOW", "RECORD MAY SNOW", "RECORD SNOW/COLD", "SNOWFALL RECORD",
    "HEAVY WET SNOW"
    ),
  c("HIGH SURF", "HEAVY SURF/HIGH SURF", "ASTRONOMICAL HIGH TIDE", "HEAVY SURF",
    "HIGH SURF ADVISORY", "ROUGH SURF", "HAZARDOUS SURF", "HEAVY SURF AND WIND",
    "HIGH SURF ADVISORIES"
    ),
  c("HIGH WIND", "HIGH WINDS", "WIND", "GUSTY WINDS", "GUSTY WIND", "GUSTY LAKE WIND",
    "HIGH WINDS/COLD", "HIGH WIND/HEAVY SNOW", "HIGH WINDS/SNOW", "HEAVY SNOW AND HIGH WINDS",
    "HIGH WIND (G40)", "HIGH WIND AND HIGH TIDES", "HIGH WIND DAMAGE",
    "HIGH WINDS 63", "HIGH WINDS 66", "HIGH WINDS 80", "SNOW/HIGH WINDS",
    "HEAVY SNOW/HIGH WIND", "HEAVY SNOW/HIGH WINDS", "HEAVY SNOW/HIGH WINDS & FLOOD",
    "HEAVY SNOW/HIGH WINDS/FREEZING", "HIGH WIND 48", "HIGH WIND 63",
    "HIGH WIND 70", "HIGH WIND AND HEAVY SNOW", "HIGH WIND AND SEAS",
    "HIGH WIND/SEAS", "HIGH WINDS 55", "HIGH WINDS 57", "HIGH WINDS 58",
    "HIGH WINDS 67", "HIGH WINDS 73", "HIGH WINDS 76", "HIGH WINDS 82",
    "HIGH WINDS/", "HIGH WINDS/FLOODING", "HURRICANE OPAL/HIGH WINDS",
    "RECORD COLD AND HIGH WIND", "WINDS", "WIND DAMAGE"
    ),
  c("HURRICANE (TYPHOON)", "HURRICANE", "HURRICANE/TYPHOON", "TYPHOON",
    "HURRICANE OPAL", "HURRICANE ERIN", "HURRICANE-GENERATED SWELLS",
    "HURRICANE EDOUARD", "HURRICANE FELIX", "HURRICANE EMILY", "HURRICANE GORDON"
    ),
  c("ICE STORM", "ICE STORM/FLASH FLOOD", "SNOW/ICE STORM", "HEAVY SNOW AND ICE STORM",
    "HEAVY SNOW/ICE STORM", "GLAZE/ICE STORM", "ICE STORM AND SNOW", "SLEET/ICE STORM",
    "SNOW AND ICE STORM"),
  c("LAKE-EFFECT SNOW", "LAKE EFFECT SNOW", "HEAVY LAKE SNOW"),
  c("LAKESHORE FLOOD", "LAKE FLOOD"),
  c("LIGHTNING", "LIGHTING", "LIGHTNING  WAUSEON", "LIGHTNING AND WINDS",
    "LIGHTNING DAMAGE", "LIGHTNING FIRE", "LIGHTNING INJURY", "LIGHTNING."
    ),
  c("MARINE HAIL"),
  c("MARINE HIGH WIND"),
  c("MARINE STRONG WIND"),
  c("MARINE THUNDERSTORM WIND", "MARINE TSTM WIND"),
  c("RIP CURRENT", "RIP CURRENTS", "RIP CURRENTS/HEAVY SURF",
    "RIP CURRENTS HEAVY SURF"
    ),
  c("SEICHE"),
  c("SLEET", "SLEET STORM", "SNOW/SLEET", "FREEZING RAIN/SLEET",
    "FREEZING RAIN AND SLEET", "SNOW/SLEET/FREEZING RAIN", "SNOW AND SLEET",
    "LIGHT SNOW AND SLEET", "SLEET/FREEZING RAIN", "SLEET/SNOW",
    "FREEZING RAIN SLEET AND", "FREEZING RAIN SLEET AND LIGHT",
    "SLEET & FREEZING RAIN", "SLEET/RAIN/SNOW", "SNOW SLEET", "SNOW/RAIN/SLEET",
    "SNOW/SLEET/RAIN"
    ),
  c("STORM SURGE/TIDE", "STORM SURGE", "COASTAL STORM", "COASTAL SURGE", "COASTALSTORM"),
  c("STRONG WIND", "STRONG WINDS", "STRONG WIND GUST", "FLOOD/STRONG WIND",
    "ICE/STRONG WINDS"
    ),
  c("THUNDERSTORM WIND", "TSTM WIND/HAIL", "TSTM WIND", "THUNDERSTORM WINDS",
    "THUNDERSTORM WINDSS", "THUNDERTORM WINDS","THUNDERSTORM WINDS LIGHTNING",
    "THUNDERSTORMS WINDS", "THUNDERSTORMS WIND", "THUNDERSTORM WIND/LIGHTNING",
    "THUNDERTSORM WIND", "THUNDERSTORM WINDS/HAIL", "THUNDERSTORM", "THUNDERSTORM WINDS HAIL",
    "TSTM WIND (G45)", "SEVERE THUNDERSTORMS", "DRY MICROBURST", "MICROBURST",
    "TSTM WIND (G40)", "TSTM WINDS", "TSTM WIND 52", "TSTM HEAVY RAIN", "TSTM WIND 55",
    "TSTM WIND 51", "TSTM", "TSTM WIND  (G45)", "TSTM WIND (41)", "TSTM WIND (G35)",
    "TSTM WIND 40", "TSTM WIND 45", "TSTM WIND 50", "TSTM WIND 65)", "TSTM WIND AND LIGHTNING",
    "TSTM WIND DAMAGE", "TSTM WIND G45", "TSTM WIND G58", "TSTM WND", "TSTMW", 
    "THUNDERSTORM  WINDS", "GUSTY THUNDERSTORM WINDS", "SEVERE THUNDERSTORM WINDS",
    "THUNDERSTORM WIND 60 MPH", "THUNDERSTORM WIND G50", "THUNDERSTORM WIND/ TREES",
    "THUNDERSTORMS", "GUSTY THUNDERSTORM WIND", "THUNDERSTORM WINDS.",
    "THUNDERSTORMW WINDS", "THUNDERSTORM DAMAGE", "THUNDERSTORM WIND 50",
    "THUNDERSTORM WIND G52", "THUNDERSTORM WIND G60", "THUNDERSTORM WINDS AND",
    "THUNDERSTORM WINDS FUNNEL CLOU", "THUNDERSTORM WINDS G", "THUNDERSTORM WINDS/ FLOOD",
    "THUNDERSTROM WINDS", "FLASH FLOODING/THUNDERSTORM WI", "LIGHTNING AND THUNDERSTORM WIN",
    "LIGHTNING THUNDERSTORM WINDS", "LIGHTNING THUNDERSTORM WINDSS",
    "THUNDERSNOW SHOWER", "THUNDERSTORM DAMAGE TO", "THUNDERSTORM HAIL", "THUNDERSTORM W INDS",
    "THUNDERSTORM WIND (G40)", "THUNDERSTORM WIND 52", "THUNDERSTORM WIND 56",
    "THUNDERSTORM WIND 59", "THUNDERSTORM WIND 59 MPH", "THUNDERSTORM WIND 59 MPH.",
    "THUNDERSTORM WIND 65 MPH", "THUNDERSTORM WIND 65MPH", "THUNDERSTORM WIND 69",
    "THUNDERSTORM WIND 98 MPH", "THUNDERSTORM WIND G51", "THUNDERSTORM WIND G55",
    "THUNDERSTORM WIND G61", "THUNDERSTORM WIND TREES", "THUNDERSTORM WIND.",
    "THUNDERSTORM WIND/ TREE", "THUNDERSTORM WIND/AWNING", "THUNDERSTORM WIND/HAIL",
    "THUNDERSTORM WINDS      LE CEN", "THUNDERSTORM WINDS 13", "THUNDERSTORM WINDS 2",
    "THUNDERSTORM WINDS 50", "THUNDERSTORM WINDS 52", "THUNDERSTORM WINDS 53",
    "THUNDERSTORM WINDS 60", "THUNDERSTORM WINDS 61", "THUNDERSTORM WINDS 62",
    "THUNDERSTORM WINDS 63 MPH", "THUNDERSTORM WINDS G60", "THUNDERSTORM WINDS HEAVY RAIN",
    "THUNDERSTORM WINDS SMALL STREA", "THUNDERSTORM WINDS URBAN FLOOD",
    "THUNDERSTORM WINDS/ HAIL", "THUNDERSTORM WINDS/FLASH FLOOD",
    "THUNDERSTORM WINDS/FLOODING", "THUNDERSTORM WINDS/FUNNEL CLOU",
    "THUNDERSTORM WINDS/HEAVY RAIN", "THUNDERSTORM WINDS53", "THUNDERSTORM WINDSHAIL",
    "THUNDERSTORM WINS", "THUNDERSTORMW", "THUNDERSTORMW 50", "THUNDERSTORMWINDS",
    "THUNDERSTROM WIND", "THUDERSTORM WINDS", "THUNDEERSTORM WINDS", "THUNDESTORM WINDS",
    "THUNDERESTORM WINDS", "THUNERSTORM WINDS", "DOWNBURST", "DOWNBURST WINDS", 
    "GUSTNADO", "GUSTNADO AND", "WET MICROBURST", "DRY MICROBURST WINDS",
    "MICROBURST WINDS", "DRY MICROBURST 58", "DRY MICROBURST 50", "DRY MICROBURST 53",
    "DRY MICROBURST 61", "DRY MICROBURST 84", "DRY MIRCOBURST WINDS", "WET MICOBURST",
    "SUMMARY JAN 17", "SUMMARY OF MARCH 14", "SUMMARY OF MARCH 23", "SUMMARY OF MARCH 24",
    "SUMMARY OF APRIL 3RD", "SUMMARY OF APRIL 12", "SUMMARY OF APRIL 13",
    "SUMMARY OF APRIL 21", "SUMMARY AUGUST 11", "SUMMARY OF APRIL 27",
    "SUMMARY OF MAY 9-10", "SUMMARY OF MAY 10", "SUMMARY OF MAY 13",
    "SUMMARY OF MAY 14", "SUMMARY OF MAY 22 AM", "SUMMARY OF MAY 22 PM",
    "SUMMARY OF MAY 26 AM", "SUMMARY OF MAY 26 PM", "SUMMARY OF MAY 31 AM",
    "SUMMARY OF MAY 31 PM", "SUMMARY OF JUNE 3", "SUMMARY OF JUNE 4",
    "SUMMARY JUNE 5-6", "SUMMARY JUNE 6", "SUMMARY OF JUNE 11", "SUMMARY OF JUNE 12",
    "SUMMARY OF JUNE 13", "SUMMARY OF JUNE 15", "SUMMARY OF JUNE 16", "SUMMARY JUNE 18-19",
    "SUMMARY OF JUNE 23", "SUMMARY OF JUNE 24", "SUMMARY OF JUNE 30", "SUMMARY OF JULY 2",
    "SUMMARY OF JULY 3", "SUMMARY OF JULY 22", "SUMMARY JULY 23-24", "SUMMARY OF JULY 26",
    "SUMMARY OF JULY 29", "SUMMARY OF AUGUST 1", "SUMMARY AUGUST 2-3", "SUMMARY AUGUST 7",
    "SUMMARY AUGUST 9", "SUMMARY AUGUST 10", "SUMMARY AUGUST 17", "SUMMARY AUGUST 21",
    "SUMMARY AUGUST 28", "SUMMARY SEPTEMBER 4", "SUMMARY SEPTEMBER 20", "SUMMARY SEPTEMBER 23",
    "SUMMARY SEPT. 25-26", "SUMMARY: OCT. 20-21", "SUMMARY: OCTOBER 31", "SUMMARY: NOV. 6-7",
    "SUMMARY: NOV. 16", "SUMMARY OF MARCH 23", "SUMMARY OF APRIL 12", "SUMMARY OF APRIL 21",
    "SUMMARY OF MAY 22", "SUMMARY OF JUNE 6", "SUMMARY AUGUST 4", "SUMMARY OF JUNE 3",
    "SUMMARY OF JUNE 10", "SUMMARY OF JUNE 13", "SUMMARY OF JUNE 18", "SUMMARY AUGUST 10",
    "SUMMARY AUGUST 11", "SUMMARY SEPTEMBER 3", "SUMMARY: SEPT. 18", "SUMMARY SEPTEMBER 23",
    "SUMMARY: NOV. 16", "SUMMARY OF MARCH 24-25", "SUMMARY OF MARCH 27", "SUMMARY OF MARCH 29",
    "TUNDERSTORM WIND"
    ),
  c("TORNADO", "FUNNEL", "WATERSPOUTS", "SEVERE THUNDERSTORM", "TORNADO F0",
    "TORNADO F1", "TORNADO F2", "TORNADO F3", "TORNADOES", "COLD AIR TORNADO",
    "TORNADO DEBRIS", "TORNADOES, TSTM WIND, HAIL", "TORNADOS", "TORNDAO",
    "COLD AIR FUNNEL", "COLD AIR FUNNELS", "FUNNELS"
  ),
  c("TROPICAL DEPRESSION"),
  c("TROPICAL STORM", "TROPICAL STORM JERRY", "TROPICAL STORM DEAN",
    "TROPICAL STORM ALBERTO", "TROPICAL STORM GORDON"
    ),
  c("TSUNAMI", "LANDSLIDE", "LANDSLIDES"),
  c("VOLCANIC ASH", "VOLCANIC ASHFALL", "VOLCANIC ERUPTION", "VOLCANIC ASH PLUME"),
  c("WATERSPOUT", "WATERSPOUT-", "WATERSPOUT/", "WATER SPOUT", "WAYTERSPOUT",
    "WATERSPOUT/TORNADO", "WATERSPOUT-TORNADO", "WATERSPOUT/ TORNADO",
    "TORNADO/WATERSPOUT", "WATERSPOUT TORNADO"
    ),
  c("WILDFIRE", "WILD/FOREST FIRE", "WILDFIRES", "WILD FIRES", "BRUSH FIRE",
    "BRUSH FIRES", "FOREST FIRES", "GRASS FIRES", "WILD/FOREST FIRES"),
  c("WINTER STORM", "WINTER STORMS", "HEAVY SNOW/WINTER STORM",
    "WINTER STORM HIGH WINDS", "WINTER STORM/HIGH WIND", "WINTER STORM/HIGH WINDS"
    ),
  c("WINTER WEATHER", "WINTER WEATHER/MIX", "FREEZING RAIN", "LIGHT FREEZING RAIN",
    "SNOW FREEZING RAIN", "SNOW/FREEZING RAIN", "FREEZING RAIN/SNOW",
    "FREEZING RAIN AND SNOW", "WINTRY MIX", "WINTER WEATHER MIX", "WINTER MIX",
    "WINTERY MIX", "FREEZING DRIZZLE"
    )
)

lookup_table <- data.frame(EVTYPE=c(), NEWEVTYPE=c())

for (i in c(1:length(replacement_list))) {
  rows <- data.frame(EVTYPE=replacement_list[[i]], NEWEVTYPE=replacement_list[[i]][1])
  lookup_table <- rbind(lookup_table, rows)
}

# Exponents table
exponents_list <- list(
  c("1e9", "B", "b"),
  c("1e6", "M", "m"),
  c("1e3", "K", "k"),
  c("1e2", "H", "h"),
  c("1e10", "10"),
  c("1e9", "9"),
  c("1e8", "8"),
  c("1e7", "7"),
  c("1e6", "6"),
  c("1e5", "5"),
  c("1e4", "4"),
  c("1e3", "3"),
  c("1e2", "2"),
  c("1e1", "1"),
  c("1e0", "0"),
  c("1", "+", "-", "?", "")
)

exponents_table <- data.frame(CURRENT=c(), NEW=c())
for (i in c(1:length(exponents_list))) {
  rows <- data.frame(CURRENT=exponents_list[[i]], NEW=exponents_list[[i]][1])
  exponents_table <- rbind(exponents_table, rows)
}

cropdmgexp_table <- exponents_table
names(cropdmgexp_table) <- c("CROPDMGEXP", "NEWCROPDMGEXP")

propdmgexp_table <- exponents_table
names(propdmgexp_table) <- c("PROPDMGEXP", "NEWPROPDMGEXP")

print(nrow(lookup_table))
print(nrow(cropdmgexp_table))
print(nrow(propdmgexp_table))

clean_data <- stormdata %>%
  mutate(EVTYPE=trimws(toupper(EVTYPE))) %>%
  left_join(lookup_table, by=(c("EVTYPE" = "EVTYPE"))) %>%
  left_join(cropdmgexp_table, by=(c("CROPDMGEXP" = "CROPDMGEXP"))) %>%
  left_join(propdmgexp_table, by=(c("PROPDMGEXP" = "PROPDMGEXP"))) %>%
  mutate(EVTYPE = as.factor(if_else(!is.na(NEWEVTYPE), NEWEVTYPE, EVTYPE))) %>%
  mutate(CROPDMGEXP = as.numeric(if_else(!is.na(NEWCROPDMGEXP), NEWCROPDMGEXP, CROPDMGEXP))) %>%
  mutate(PROPDMGEXP = as.numeric(if_else(!is.na(NEWPROPDMGEXP), NEWPROPDMGEXP, PROPDMGEXP))) %>%
  mutate(CROPDMG_AMOUNT = CROPDMG * CROPDMGEXP) %>%
  mutate(PROPDMG_AMOUNT = PROPDMG * PROPDMGEXP) %>%
  mutate(POPULATION_AMOUNT = INJURIES + FATALITIES) %>%
  mutate(ECONOMIC_AMOUNT = CROPDMG_AMOUNT + PROPDMG_AMOUNT) %>%
  mutate(BGN_YEAR = year(mdy_hms(BGN_DATE))) %>%
  #mutate(BGN_DATE = mdy_hms(BGN_DATE)) %>%
  #mutate(BGN_DATE = mdy(sapply(strsplit(BGN_DATE, " "), "[[", 1))) %>%
  #mutate(BGN_TIME = hms(if_else(
  #         nchar(BGN_TIME) != 3,
  #         if_else(
  #           nchar(BGN_TIME) == 4,
  #           gsub("(.{2})(.{2})", "\\1:\\2:00", BGN_TIME),
  #           BGN_TIME
  #         ),
  #         "00:00:00")
  #       )) %>%
  # select(BGN_YEAR, COUNTYNAME, STATE, EVTYPE, INJURIES, FATALITIES, 
  #        PROPDMG_AMOUNT, CROPDMG_AMOUNT,
  #        POPULATION_AMOUNT, ECONOMIC_AMOUNT, REFNUM) %>%
  distinct(REFNUM, .keep_all = TRUE) %>%
  group_by(BGN_YEAR, EVTYPE)

print(nrow(clean_data) - nrow(stormdata))

ref <- clean_data %>%
  group_by(REFNUM) %>%
  summarise(count=n()) %>%
  arrange(desc(count), .by_group = TRUE) %>%
  filter(count > 1) %>%
  print
  

remaining <- filter(clean_data, !EVTYPE %in% official_event_types) %>%
  group_by(EVTYPE) %>%
  summarise(count=n()) %>%
  arrange(desc(count), .by_group = TRUE) %>%
  print

print(nrow(clean_data))

# Official events only
clean_data <- clean_data[clean_data$EVTYPE %in% official_event_types,]

print(nrow(clean_data))

# Event types by year
event_types_by_year <- clean_data %>%
  select(BGN_YEAR, EVTYPE) %>%
  unique %>%
  aggregate(EVTYPE ~ BGN_YEAR, data=., FUN = length)
event_types_by_year <- event_types_by_year[event_types_by_year$EVTYPE > 3,]

print(event_types_by_year)

# Filter clean data
clean_data <- clean_data[clean_data$BGN_YEAR %in% event_types_by_year$BGN_YEAR,] %>%
  ungroup(BGN_YEAR)

print(nrow(clean_data))

# Impacts
event_impacts <- clean_data %>%
  summarise(POPULATION_IMPACT = sum(POPULATION_AMOUNT),
            ECONOMIC_IMPACT = sum(ECONOMIC_AMOUNT))
  
  

# Summarize population impact
population_impacts <- event_impacts %>%
  arrange(desc(POPULATION_IMPACT)) %>%
  .[, c("EVTYPE", "POPULATION_IMPACT")] %>%
  print

# Summarize economic impact
economic_impacts <- event_impacts %>%
  arrange(desc(ECONOMIC_IMPACT)) %>%
  .[, c("EVTYPE", "ECONOMIC_IMPACT")] %>%
  print

par(mfrow=c(1, 2))
barplot(height = population_impacts$POPULATION_IMPACT, names=population_impacts$EVTYPE,
        horiz = TRUE, las=1, cex.names = .5, cex.axis = .8, col="#69b3a2")

barplot(height = economic_impacts$ECONOMIC_IMPACT, names=economic_impacts$EVTYPE,
        horiz = TRUE, las=1, cex.names = .5, cex.axis = .8, col="#69b3a2")
